version: '3.3'
services:
  springdocker:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:9-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    restart: always
